<div>
	<div  style="width:100%; height:910px">
        <iframe src="<?php echo Mage::helper('salesanalytics/url')->getTPSALoginUrl() ?>?token=<?php echo Mage::getSingleton('terapeak_salesanalytics/usersession')->getSession() ?>&email=<?php echo Mage::getSingleton('terapeak_salesanalytics/usercredentials')->load('1')->getUsername(); ?>&context=iframe,tpmysales" style="width:100%; height:900px">
		</iframe>
	</div>
</div>
<?php
    $loadHistory = Mage::getSingleton('terapeak_salesanalytics/loadhistory')->getHistory();
    if ($loadHistory) {
        echo("<script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js\"></script>");
             echo("<script>");
             echo("jQuery.noConflict();");
             echo("</script>");
        
        echo("<script type=\"text/javascript\">");
        echo("function loadHistory() {jQuery.get('");
        echo(Mage::helper('adminhtml')->getUrl('salesanalytics/index/loadhistory'));
        echo("', function(data) {var result = JSON.parse(data); var prodLoadPercent = (result.prods_filled / result.prods_avail);var orderLoadPercent = (result.orders_filled / result.orders_avail);if (prodLoadPercent > 1) {prodLoadPercent=1;} if (orderLoadPercent > 1) {orderLoadPercent=1;}  if (prodLoadPercent < 1 || orderLoadPercent < 1) {setTimeout(\"loadHistory()\", 500);}});}");
        echo("jQuery(document).ready(function() {loadHistory(); });");
        echo("</script>");

    }
             ?>
        
    
