<?php
    $data	=	$this->getLoadedProductCollection();
	//echo '<pre>';print_r($data);
    $_helper = $this->helper('catalog/output');
?>
<?php if(count($data) == 0): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="deal-products"> 
    <h4>Deal</h4> 
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($data as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($data) ): ?> last<?php endif; ?>">		
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(165); ?>" width="165" height="165" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getShortName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
    <?php 
		$config	=	$this->getConfigs();
		if($config['toolbar']	==	1)
		{
		$pager = $this->getLayout()->createBlock('page/html_pager');
		echo $this->getToolbarBlock()->setCollection($data)->setTemplate('em_productsfilterwidget/toolbar.phtml')->setChild('product_list_toolbar_pager',$pager)->toHtml(); 
		}
	
	?>
</div>
<?php endif; ?>
	
