<?php
/**
 * Mageix LLC
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to Mageix LLC's  End User License Agreement
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ixcba.com/index.php/license-guide/
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to webmaster@ixcba.com so we can send you a copy immediately.
 *
 * DISCLAIMER

 *
 * @category	Mageix
 * @package 	Mageix_Ixcbadv
 * @copyright   Copyright (c) 2011 Mageix LLC (http://ixcba.com)
 * @license	http://ixcba.com/index.php/license-guide/  End User License Agreement
 */

/*
 * Magento Mageix IXCBA Module
 *
 * @category   Checkout & Payments
 * @package	Mageix_Ixcbadv
 * @copyright  Copyright (c) 2011 Mageix LLC (http://ixcba.com)
 * @developer  Brian Graham
  *@licence 	http://ixcba.com/index.php/license-guide/ 
 */

?>
<?php
    $_value = $this->getTotal()->getValue();
    $_style = $this->getTotal()->getStyle();
?>
<?php global $taxIter; $taxIter++; ?>
<?php if ($this->helper('tax')->displayFullSummary() && $_value!=0): ?>
<?php $isTop = 1; ?>
    <?php foreach ($this->getTotal()->getFullInfo() as $info): ?>
        <?php if (isset($info['hidden']) && $info['hidden']) continue; ?>
        <?php $percent = $info['percent']; ?>
        <?php $amount = $info['amount']; ?>
        <?php $rates = $info['rates']; ?>
        <?php $isFirst = 1; ?>

        <?php foreach ($rates as $rate): ?>
        <tr class="summary-details-<?php echo $taxIter; ?> summary-details<?php if ($isTop): echo ' summary-details-first'; endif; ?>" style="display:none;">
            <td class="a-left" style="<?php echo $_style ?>" colspan="<?php echo $this->getColspan(); ?>">
                <?php echo $this->escapeHtml($rate['title']); ?>
                <?php if (!is_null($rate['percent'])): ?>
                    (<?php echo (float)$rate['percent']; ?>%)
                <?php endif; ?> :
                <br />
            </td>
            <?php if ($isFirst): ?>
                <td style="<?php echo $_style ?>" class="a-right" rowspan="<?php echo count($rates); ?>">
                    <?php echo $this->helper('checkout')->formatPrice($amount); ?>
                </td>
            <?php endif; ?>
        </tr>
        <?php $isFirst = 0; ?>
        <?php $isTop = 0; ?>
        <?php endforeach; ?>
    <?php endforeach; ?>
<?php endif;?>
<tr <?php if ($this->helper('tax')->displayFullSummary() && $_value!=0): ?> class="summary-total" onclick="expandDetails(this, '.summary-details-<?php echo $taxIter;?>')"<?php endif; ?>>
    <td style="<?php echo $_style ?>" class="a-left" colspan="<?php echo $this->getColspan(); ?>">
        <?php if ($this->helper('tax')->displayFullSummary()): ?>
            <div class="summary-collapse"><?php echo $this->getTotal()->getTitle() ?> :</div>
        <?php else: ?>
            <?php echo $this->getTotal()->getTitle() ?> :
        <?php endif;?>
    </td>
    <td style="<?php echo $_style ?>" class="a-right"><?php echo $this->helper('checkout')->formatPrice($_value) ?></td>
</tr>
