
<div class="header-top checkout">
    <div class="container">
        <img src="<?php echo $this->getSkinUrl('images/logo-tiny.png') ?>" alt="<?php echo $this->getLogoAlt() ?>" class="header-top-logo" />
    </div>
</div>
<header id="header" class="page-header checkout">
    <div class="page-header-container">
        <div class="secure-checkout">
            <span><i class="icon icon-lock"></i>Secure Checkout</span>
        </div>
        <a class="logo" href="<?php echo $this->getUrl('') ?>">
            <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="large" />
            <img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="small" />
        </a>

        <?php if( Mage::getModel('cms/block')->load('header_phone')->getIsActive() ){ ?>
        <div class="phone">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('header_phone_checkout')->toHtml();?>
        </div>
        <?php } ?>

    </div>
</header>
<?php echo $this->getChildHtml('topContainer'); ?>
