<div class="modal fade" id="modal-sizing">
  <div class="modal-dialog">
    <div class="modal-content">
        <h4>Size Charts</h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <div class="modal-body">
        <div class="print-header">
            <img src="<?php echo $this->getSkinUrl('images/logo_small.png') ?>" alt="Bling Jewelry" />
        </div>
        <div class="product-sizing toggle-content tabs">
            <dl id="sizing-tabs" class="sizing-tabs">
                <dt class="tab"><span>Ring</span></dt>
                <dd class="tab-container">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('sizing_ring')->toHtml() ?>
                </dd>
                <dt class="tab"><span>Necklace</span></dt>
                <dd class="tab-container">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('sizing_necklace')->toHtml() ?>
                </dd>
                <dt class="tab"><span>Bracelet</span></dt>
                <dd class="tab-container">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('sizing_bracelet')->toHtml() ?>
                </dd>
                <dt class="tab"><span>CZ</span></dt>
                <dd class="tab-container">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('sizing_cz')->toHtml() ?>
                </dd>
            </dl>
        </div>

      </div><!-- /.modal-body -->
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->