<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>

<?php //echo $this->getChildHtml('catalog.leftnav'); /* mmc add layered nav */ ?>
<?php // mmc bling added for celebros ?>
<?php echo $this->getChildHtml('leadquestion_top') ?>
<?php echo $this->getChildHtml('nonleadquestions_top') ?>

<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                <?php /* Based on the native RWD styling, product images are displayed at a max of ~400px wide when viewed on a
                        one column page layout with four product columns from a 1280px viewport. For bandwidth reasons,
                        we are going to serve a 300px image, as it will look fine at 400px and most of the times, the image
                        will be displayed at a smaller size (eg, if two column are being used or viewport is smaller than 1280px).
                        This $_imgSize value could even be decreased further, based on the page layout
                        (one column, two column, three column) and number of product columns. */ ?>
                <?php $_imgSize = 300; ?>
                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize($_imgSize); ?>"
                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
            </a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <div class="product-primary">
                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                        <?php if($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product) ?>
                        <?php endif; ?>

                        <?php
                            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                            foreach($_nameAfterChildren as $_nameAfterChildName):
                                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                $_nameAfterChild->setProduct($_product);
                        ?>
                            <?php echo $_nameAfterChild->toHtml(); ?>
                        <?php endforeach; ?>
                    </div>
                    <div class="product-secondary">
                        <?php echo $this->getPriceHtml($_product, true) ?>
                    </div>
                    <!-- ADD -->
                    <div class="product-secondary">
                        <button type="button" title="<?php echo $this->__('Quick View') ?>" class="button btn-quick-view" onclick="showQuickview('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Quick View') ?></span></span></button>
                    </div>
                    <!-- END ADD -->

                    <div class="product-secondary">
                        <?php if($_product->isSaleable() && !$_product->canConfigure()): ?>
                        <!-- ADD -->
                    	<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
                            <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                            <span id='ajax_loader<?php echo $_product->getId()?>' style='display:none' class="ajax-cart-loader"><img src='<?php echo $this->getSkinUrl('images/ajax/ajax-loader.gif')?>'/></span>
                        <?php } else { ?>
                        	<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php } ?>
                        <!-- END ADD -->
                        <?php elseif($_product->isSaleable()): ?>
                            <p class="action"><a title="<?php echo $this->__('View Details') ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a></p>
                        <?php else: ?>
                            <p class="action availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                 <!-- ADD -->
                                 <li>
                                 <a href="#" onclick='ajaxWishlist("<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>","<?php echo $_product->getId()?>");return false;' class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                                 <span id='ajax_wishlist_loader<?php echo $_product->getId()?>' style='display:none' class="ajax-wishlist-loader"><img src='<?php echo $this->getSkinUrl('images/ajax/ajax-loader.gif')?>'/></span>
                                 </li>
                                 <!-- END ADD -->
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                 <!-- ADD -->
                            <li>
                            	<span class="separator">|</span> <a href="#" onclick='ajaxCompare("<?php echo $_compareUrl ?>","<?php echo $_product->getId()?>");return false;' class="link-compare"><?php echo $this->__('Add to Compare') ?></a>
                            	<span id='ajax_compare_loader<?php echo $_product->getId()?>' style='display:none' class="ajax-compare-loader"><img src='<?php echo $this->getSkinUrl('images/ajax/ajax-loader.gif')?>'/></span>
                            </li>
                                 <!-- END ADD -->
                            <?php endif; ?>
                        </ul>
                    </div>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
            <?php /*if ($i++%$_columnCount==0): ?>
            <?php endif*/ ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php $_imgSize = 210; ?>
                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" width="<?php echo $_imgSize;?>" height="<?php echo $_imgSize;?>" />

                        <?php /* hide quickview
                        <!-- ADD -->
                        <a href='<?php echo $this->getUrl('ajax/index/quickview',array('product_id'=>$_product->getId()));?>' id='quickview<?php echo $_product->getId()?>' class="button js-btn-quickview" data-pid="<?php echo $_product->getId()?>">Quickview</a> 
                        <!-- END ADD -->
                        */?>
                        <span class="badge new">
                            <?php
                            $newFromDate = $_product->getNewsFromDate();
                            $newToDate = $_product->getNewsToDate();
                            $now = Mage::app()->getLocale()->date()->toString(Varien_Date::DATETIME_INTERNAL_FORMAT);
                            if(($newFromDate < $now && $newFromDate != NULL) && ($newToDate > $now || $newToDate == "")){
                                echo "New!";
                            }
                            ?>
                        </span>

                </a>

                <?php
                // bling added short title logic
                $shortTitle = $_product->getShortTitle();
                if(!empty($shortTitle)){
                    $_productName = $this->escapeHtml($shortTitle);
                }else{
                    $_productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
                }
                ?>
                <div class="product-info">
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productName;?>"><?php echo $_productName;?></a></h2>

                   <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <!-- ADD -->
                     <span class="ajax-wishlist-button">
                        <a href="#" onclick='ajaxWishlist("<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>","<?php echo $_product->getId()?>");return false;' class="link-wishlist"><i class="icon-heart"></i>
                        <span id='ajax_wishlist_loader<?php echo $_product->getId()?>' style='display:none' class="ajax-wishlist-loader"><img src='<?php echo $this->getSkinUrl('images/ajax/ajax-loader.gif')?>'/></span>
                        </a>
                     </span>
                    <!-- END ADD -->
                    <?php endif; ?>

                    <?php
                        $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                        foreach($_nameAfterChildren as $_nameAfterChildName):
                            $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                            $_nameAfterChild->setProduct($_product);
                    ?>
                        <?php echo $_nameAfterChild->toHtml(); ?>
                    <?php endforeach; ?>

                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php /* remove ratings
                     if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php endif; 
                    */?>
                    <?php if(!$_product->isSaleable()): ?>
                    <p class="availability out-of-stock"><span><?php echo $this->__('Waitlist') ?></span></p>
                    <?php endif; ?>

                    <?php /* turn off ajax add to cart/options, add to cart etc located here

                    <div class="actions">
                        <?php //original condition if($_product->isSaleable() && !$_product->canConfigure()): ?>
                            if($_product->isSaleable()):
                            <!-- ADD -->
                            <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php } else { ?>
                                <a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' id='ajaxoptions<?php echo $_product->getId()?>' class="button js-btn-options" data-pid="<?php echo $_product->getId()?>"><span><span><?php echo $this->__('Add to Cart') ?></span></span></a>
                            <?php }  ?>
                            <span id='ajax_loader<?php echo $_product->getId()?>' style='display:none' class="ajax-cart-loader"><img src='<?php echo $this->getSkinUrl('images/ajax/ajax-loader.gif')?>'/></span>
                            <!-- END ADD -->
                            <?php // removing view details since have the option popup 
                                //elseif($_product->isSaleable()): ?>
                                //<a title="<?php echo $this->__('View Details') ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a> 
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Waitlist') ?></span></p>
                        <?php endif; ?>
                        */?>
                        <?php /* remove compare
                        <ul class="add-to-links">
                            
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <!-- ADD -->
                            <li>
                               <span class="separator">|</span> <a href="#" onclick='ajaxCompare("<?php echo $_compareUrl ?>","<?php echo $_product->getId()?>");return false;' class="link-compare"><?php echo $this->__('Add to Compare') ?></a>
                               <span id='ajax_compare_loader<?php echo $_product->getId()?>' style='display:none' class="ajax-compare-loader"><img src='<?php echo $this->getSkinUrl('images/ajax/ajax-loader.gif')?>'/></span>
                            </li>
                            <!-- END ADD -->
                            <?php endif; ?>
                            
                        </ul>
                        
                    </div>

                    */?>
                </div>
            </li>
            <?php /*if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            <?php endif*/ ?>
        <?php endforeach ?>
    </ul>
    <?php /*<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script> */?>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>

<?php
    //set product collection on after blocks
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach($_afterChildren as $_afterChildName):
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        $_afterChild->setProductCollection($_productCollection);
    ?>
    <?php echo $_afterChild->toHtml(); ?>
<?php endforeach; ?>



<script type="text/javascript">

    // grabs data from quickview or options modal or this page
	function setAjaxData(data,iframe){
		if(data.status == 'ERROR'){
			alert(data.message);
		}else{
            if(jQuery('.block-cart')){
                jQuery('.block-cart').html(data.minicart_content);
                jQuery('.header-minicart .count').html(data.minicart_count);
                jQuery('.header-minicart .skip-cart, #header-cart').addClass('skip-active');
                jQuery('.header-minicart .skip-cart').removeClass('no-count');
            }
            $j('#qv-modal').modal('hide');
		}
	}
    // ajax add to cart button
	function setLocationAjax(url,id){
		url += 'isAjax/1';
		url = url.replace("checkout/cart","ajax/index");
		jQuery('#ajax_loader'+id).show();
		try {
			jQuery.ajax( {
				url : url,
				dataType : 'json',
				success : function(data) {
					jQuery('#ajax_loader'+id).hide();
         			setAjaxData(data,false);           
				}
			});
		} catch (e) {
		}
	}
    // todo add to app.js
    // todo fix wishlist add to sidebar
    // quickview modal
    $j('.js-btn-quickview').on('click', function(e){
        e.preventDefault();
        // prepare modal but hide

        var id = $j(this).data('pid');
        var url = $j(this).attr('href');
        var qvModal = $j('#qv-modal'),
            modalBody = qvModal.find('.modal-body');

        // prod not needed $j("#myModal").modal('hide');
        $j('#ajax_loader'+id).show();

        // load content into modal
        modalBody.html('<iframe width="100%" height="100%" frameborder="0" scrolling="yes" allowtransparency="true" src="'+url+'"></iframe>');
        //show modal

        $j('#qv-modal iframe').load(function() {
            $j('#ajax_loader'+id).hide();
            $j('#qv-modal').modal({backdrop:false});
        });
    });
    // quickview modal
    $j('.js-btn-options').on('click', function(e){
        e.preventDefault();
        // prepare modal but hide

        var id = $j(this).data('pid');
        var url = $j(this).attr('href');
        var qvModal = $j('#qv-modal'),
            modalBody = qvModal.find('.modal-body');

        // prod not needed $j("#myModal").modal('hide');
        $j('#ajax_loader'+id).show();

        // load content into modal
        modalBody.html('<iframe width="100%" height="100%" frameborder="0" scrolling="yes" allowtransparency="true" src="'+url+'"></iframe>');
        //show modal

        $j('#qv-modal iframe').load(function() {
            $j('#ajax_loader'+id).hide();
            $j('#qv-modal').modal({backdrop:false});
        });
    });
</script>

<!-- QV Modal -->
<div class="modal fade" id="qv-modal" tabindex="-1" role="dialog" aria-labelledby="qvModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
      </div>
      </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->