<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php
// bling added short title logic
$shortTitle = $_product->getShortTitle();
if(!empty($shortTitle)){
    $mainTitle = $this->escapeHtml($shortTitle);
    $subTitle = $_helper->productAttribute($_product, $_product->getName(), 'name');
}else{
    $mainTitle = $_helper->productAttribute($_product, $_product->getName(), 'name');
    $subTitle = '';
}
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view<?php if($this->getChildHtml('related_products')){?> has-related<?php } ?>">
    <div class="product-essential">
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>

            <div class="product-top-wrap">
            <div class="product-img-box">
                <div class="product-name">
                    <h1><?php echo $mainTitle ?></h1>
                </div>
                <?php echo $this->getChildHtml('media') ?>
            </div>

            <div class="product-shop">
                <div class="product-name">
                    <?php // bling added;?>
                    <span class="h1"><?php echo $mainTitle ?></span>
                </div>
                <?php if(!empty($subTitle)){?>
                <h1 class="product-sub-name"><?php echo $subTitle;?></h1>
                <?php } ?>

                <div class="extra-info">
                    <div class="sku"><?php echo $_product->getSku() ;?></div>
                    <?php // true shows when no result, default/short is other option
                    echo $this->getReviewsSummaryHtml($_product, 'default', true)?>
                </div>

                <?php /* if ($_product->getShortDescription()):?>
                    <div class="short-description">
                        <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                    </div>
                <?php endif; */ ?>


                <?php  
                // bling added
                $_useMsrp = false;
                $_regularPrice = $this->helper('tax')->getPrice($_product, $_product->getPrice());
                $_msrp = $this->helper('tax')->getPrice($_product,$_product->getMsrp());
                $_finalPrice = $this->helper('tax')->getPrice($_product, $_product->getFinalPrice());

                // first determine if a sale
                if($_finalPrice < $_regularPrice){
                    // sale
                    $disc = $_regularPrice - $_finalPrice;
                    $basis = $_regularPrice;
                }
                if(($_msrp > $_regularPrice) && ($_msrp > $_finalPrice)){
                    // msrp situation
                    $disc = $_msrp - $_finalPrice;
                    $basis = $_msrp;
                    $_useMsrp = true;
                }
                $_freeShipping = false;
                if($_finalPrice >= 20){
                    $_freeShipping = true;
                }
                if(!empty($basis)){
                    $getpercentage = number_format(($disc/$basis)*100, 2);
                }
                ?>
                <div class="price-wrap">
                    <div class="price-info <?php if($_useMsrp){ ?>with-msrp<?php } ?>">
                        <?php
                        // bling add msrp
                        if(($_msrp > $_regularPrice) && ($_msrp > $_finalPrice)){ ?>
                            <div class="msrp"><div class="price"><?php echo Mage::helper('core')->currency($_product->getMsrp(),true,false); ?></div></div>
                        <?php } ?>
                        <?php echo $this->getPriceHtml($_product); ?>
                        <?php echo $this->getChildHtml('bundle_prices') ?>
                        <?php echo $this->getTierPriceHtml() ?>
                    </div>
                    <?php
                    if(isset($getpercentage) && !empty($getpercentage)){
                        echo '<div class="savingbox">'.number_format($getpercentage, 0).'% Savings</div>' ;
                    }
                    ?>
                    <?php 
                    //mmc  todo make sure works with cache and options
                    if($_freeShipping){ ?>
                        <span class="freeship-msg">Ships Free!</span>
                    <?php } ?>
                    <?php echo $this->getChildHtml('product_type_availability'); ?>

                </div>

                <?php echo $this->getChildHtml('alert_urls') ?>

                <?php echo $this->getChildHtml('other');?>

                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php endif;?>


                <div class="add-to-cart-wrapper">
                    <?php echo $this->getChildHtml('product_type_data') ?>
                    <?php echo $this->getChildHtml('extrahint') ?>

                    <?php if (!$this->hasOptions()):?>
                        <div class="add-to-box">
                            <?php if($_product->isSaleable()): ?>
                                <?php echo $this->getChildHtml('addtocart') ?>
                                <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                                    <span class="or"><?php echo $this->__('OR') ?></span>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php echo $this->getChildHtml('addto') ?>
                            <?php $this->getChildHtml('sharing') ?>
                        </div>
                        <?php echo $this->getChildHtml('extra_buttons') ?>
                    <?php endif; ?>
                </div>
                <div class="product-collateral toggle-content tabs accordion-open">
                    <?php if ($detailedInfoGroup = $this->getChildGroup('detailed_info', 'getChildHtml')):?>
                        <dl id="collateral-tabs" class="collateral-tabs">
                            <?php foreach ($detailedInfoGroup as $alias => $html):?>
                                <dt class="tab"><span><?php echo $this->escapeHtml($this->getChildData($alias, 'title')) ?></span></dt>
                                <dd class="tab-container">
                                    <div class="tab-content"><?php echo $html ?></div>
                                </dd>
                            <?php endforeach;?>
                        </dl>
                    <?php endif; ?>
                </div>
            </div>
            </div> <!-- close product top wrap -->

            <?php echo $this->getChildHtml('related_products') ?>

            <div class="clearer"></div>
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            <?php endif;?>
        </form>
        <script type="text/javascript">
        //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
        	productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;
                    if (url) {
                        form.action = url;
                    }
                    var e = null;
                    // Start of our new ajax code
                    if (!url) {
                        url = jQuery('#product_addtocart_form').attr('action');
                    }
                    url = url.replace("checkout/cart","ajax/index"); // New Code
                    var data = jQuery('#product_addtocart_form').serialize();
                    data += '&isAjax=1';
                    jQuery('#ajax_loader').show();
                    try {
                        jQuery.ajax( {
                          url : url,
                            dataType : 'json',
                            type : 'post',
                            data : data,
                            success : function(data) {
                            jQuery('#ajax_loader').hide();
                            if(data.status == 'ERROR'){
                                alert(data.message);
                            }else{
                                if(jQuery('.block-cart')){
                                    jQuery('.block-cart').html(data.minicart_content);
                                    jQuery('.header-minicart .count').html(data.minicart_count);
                                    jQuery('.header-minicart .skip-cart, #header-cart').addClass('skip-active');
                                    jQuery('.header-minicart .skip-cart').removeClass('no-count');
                                }
                            }
                        }
                    });
                    } catch (e) {
                    }
                    // End of our new ajax code
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }
                }
            }.bind(productAddToCartForm);
            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);


            // link stock alert modal login
            $j(".link-stock-alert a").on('click',function(e){
                e.preventDefault();
                $j('#modal-login').modal();
                $j('#signup-block,#reset-block,#login-spinner,.success,.error').hide();
                $j('#login-block .error').html('Please login or create an account').show();
                $j('#login-block').show();
            });
        //]]>
        </script>
    </div>

    <?php echo $this->getChildHtml('upsell_products') ?>
    <?php echo $this->getChildHtml('recently_viewed') ?>
    <?php echo $this->getChildHtml('product_additional_data') ?>
    <?php echo $this->getChildHtml('reviews') ?>

</div>

<?php // bling added treepodia ?>
<script type="text/javascript">
// Grab the product SKU / Code
var trpdSKU = '<?php echo $this->htmlEscape($_product->getSku()) ?>';

var video; var product;
function initTreepodia() { product = Treepodia.getProduct('UA-BLINGJEWELRY1', trpdSKU); product.requestVideo(handleVideo); }
function handleVideo(vid) { video = vid; if (vid.hasVideos()) { video.setPlayer("default"); video.setChromeless(true);} else { document.getElementById('video-btn').style.display = 'none'; } }
</script>

<script type="text/javascript">
// Include Dialog Script
document.write(unescape("%3Cscript src='" + document.location.protocol + "//dxa05szpct2ws.cloudfront.net/utils/trpdDialog/video-dialog.min.js' type='text/javascript'%3E%3C/script%3E"));
</script>

<script type="text/javascript">
// Include Treepodia main script
document.write(unescape("%3Cscript src='" + document.location.protocol + "//dxa05szpct2ws.cloudfront.net/TreepodiaAsyncLoader.js' type='text/javascript'%3E%3C/script%3E"));
</script>