<?php
    $_category  = Mage::registry('current_category');
    $_helper    = Mage::helper('catalog/output');
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" />';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
        global $categoryHero;
        $categoryHero = 1;
    }
?>
<?php if($_imgUrl): ?>
<div class="category-hero">
<?php echo $_imgHtml ?>

					<div class="category-description">
    					<h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
						<?php /* if($_category->getDescription()): ?>
    					<div class="description">
        					<?php echo $_helper->categoryAttribute($_category, $_category->getDescription(), 'description') ?>
    					</div>
    					<?php endif; */ ?> 
    				</div>
 
</div>
<?php endif;?>
