<?php if (Mage::getStoreConfig('mybuys_websitecode/general/website_code') == 'enabled') : ?>
<?php $_quote = Mage::getSingleton('checkout/session')->getQuote(); ?>
<?php $orderEmail = $_quote->getCustomerEmail(); ?>
<?php $subscriber = Mage::getModel('newsletter/subscriber')->loadByEmail($orderEmail); ?>
<?php $_totals = $_quote->getTotals(); ?>
<?php $_subtotal = $_totals["subtotal"]->getValue(); ?>

<script type="text/javascript">
mybuys.setPageType("SHOPPING_CART");
mybuys.set("email","<?php echo $orderEmail ?>");
mybuys.set("amount","<?php echo money_format('%.2n',$_subtotal) ?>");
mybuys.set("optin","<?php echo $subscriber->isSubscribed()?"y":"n";?>");
</script>

<script type="text/javascript">
<?php $cartItems = $_quote->getAllItems(); ?>
<?php foreach ($cartItems as $item) : ?>
<?php $product = $item->getProduct();  ?>
<?php if($item->getParentItem()) : ?>
    <?php if($item->getParentItem()->getProduct()->getTypeId() == 'bundle') : ?>
        mybuys.addCartItemQtySubtotal("<?php echo $product->getId(); ?>","<?php echo $item->getQty(); ?>","0.00");
    <?php else: ?>
        mybuys.addCartItemQtySubtotal("<?php echo $product->getId(); ?>","<?php echo $item->getQty(); ?>","<?php echo money_format('%.2n',$item->getRowTotal()); ?>");
    <?php endif; ?> 
<?php else: ?>
        mybuys.addCartItemQtySubtotal("<?php echo $product->getId(); ?>","<?php echo $item->getQty(); ?>","<?php echo money_format('%.2n',$item->getRowTotal()); ?>");
<?php endif; ?> 
<?php endforeach; ?>
</script>
<?php endif; ?>