<div class="page-title">
	<h1>Press</h1>
</div>

<?php 
if(Mage::getModel('cms/block')->load('press')->getIsActive()){
echo $this->getLayout()->createBlock('cms/block')->setBlockId('press')->toHtml();
}
?>


<div class="row">
<ul class="press">
<?php echo $this->_listPress();?>
</ul>
</div>

<a href="#" id="prev" class="press-nav">prev</a>
<a href="#" id="next" class="press-nav">next</a>

<script>

// cache container

var $container = jQuery('.press');

// initialize isotope
$container.isotope({
  itemSelector : '.press-item',
  layoutMode : 'masonry',
  filter: '.editorial'
});

// filter items when filter link is clicked
jQuery('.nav-horiz a').click(function(){
  var selector = jQuery(this).attr('data-filter');
  if(jQuery(window).width()>979){
  if(selector == '.video'){
  	jQuery('.iso-wrap').width(840);
  }else{
  	jQuery('.iso-wrap').width(724);	
  }
  }
  $container.isotope({ filter: selector });
  return false;
});

jQuery(document).ready(function(){
	jQuery('.press-item a.image').click(function(e){
		e.preventDefault();
	
		var cl = jQuery(this).attr('class');
		
		var item = jQuery(this).closest('li');
		prev = jQuery(item).prev('li');
		next = jQuery(item).next('li');	
		
		if(prev.length == 0){
			jQuery('#prev').hide();
		}else{
			jQuery('#prev').show();			
		}
		if(next.length == 0){
			jQuery('#next').hide();
		}else{
			jQuery('#next').show();		
		}
		
		var img 		= jQuery(this).attr('href');
		var title 		= jQuery(this).closest('.image-wrap').next('.title-wrap').find('h3 > a').text();
		var subtitle 	= jQuery(this).closest('.image-wrap').next('.title-wrap').find('h4').text();
		var date 		= jQuery(this).closest('.image-wrap').next('.title-wrap').find('.date').text();
		var vid			= jQuery(this).closest('.image-wrap').next('.title-wrap').find('.vid').html();

		if(cl=='image'){
			jQuery('body').append('<div class="press-detail"><div><img src="'+ img +'"><div class="clearfix"></div></div></div>');
		}
		if(cl=='video'){
			jQuery('body').append('<div class="press-detail"><div>'+vid+'</div></div>');
		}
		
		if(document.getElementById("modalBackdrop")){
			jQuery('.press-detail').fadeIn();
			jQuery('#title').text(title);
			jQuery('#subtitle').text(subtitle);
			jQuery('#date').text(date);	
		}else{
			var header = '<div class="press-header" id="pressHeader">';
			header += '<span id="title">'+ title +'</span>';
			header += '<span id="subtitle">'+ subtitle +'</span>';
			header += '<span id="date">'+ date +'</span>';
			header += '<span id="close"><button type="button" class="close" data-dismiss="modal" aria-hidden="true" autocomplete="off">×</button></span>';	
			header += '</div>';
			jQuery('body').append(header);
			jQuery('body').append('<div class="modal-backdrop" id="modalBackdrop"></div>');
			jQuery('.modal-backdrop').addClass('in');	
			jQuery('.press-detail').fadeIn();
		}
	});
	jQuery(document).on('click','.press-detail,.close',function(){
		jQuery('.modal-backdrop,.press-header,.press-detail,.press-nav').fadeOut('normal', function(){
			jQuery('.modal-backdrop,.press-header,.press-detail').remove();
		});	
	});
	jQuery(document).on('click','#next',function(){
		jQuery('.press-detail').fadeOut('fast', function(){
			jQuery(this).remove();
			jQuery(next).find('.image-wrap a').trigger('click');
		});
		
	});	
	jQuery(document).on('click','#prev',function(){
		jQuery('.press-detail').fadeOut('fast', function(){
			jQuery(this).remove();
			jQuery(prev).find('.image-wrap a').trigger('click');
		});
	});
});
</script>