<?php 
// mmc add success block
if(Mage::getModel('cms/block')->load('cart_success')->getIsActive()){ ?>
<div class="cart-success">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('cart_success')->toHtml(); ?>
</div>
<?php } ?>
<?php
if ($this->horizontalShareEnable() == "1" && $this->horizontalShareSuccess() == "1") {
    if (trim($this->sharingTitle()) != "") {
        echo '<div style="font-weight:bold">'.__(trim($this->sharingTitle())).'</div>';
    }
    echo '<div class="loginRadiusHorizontalSharing"></div>';
}
if ($this->verticalShareEnable() == "1" && $this->verticalShareSuccess() == "1") {
    echo '<div class="loginRadiusVerticalSharing"></div>';
}