<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_Promo
 */
?>
<?php
$products = Mage::helper('ampromo')->getNewItems();
?>
<?php if (sizeof($products) > 0): ?>
    <div id="ampromo-items-add"><?php echo Mage::getStoreConfig('ampromo/general/add_message')?></div>
    <script type="text/javascript">
        var button = $('ampromo-items-add').down('a');
        button.observe('click', ampromo_check_initialization);
        if (window.location.hash == '#choose-gift') {
            Event.observe(window, 'load', function() {
                button.click();
            });
        }
    </script>
<?php endif ?>
