<?php /* @var $this Bronto_Common_Block_Adminhtml_System_Config_Guide */ ?>

<?php if ($this->isBrontoSection('bronto_reviews')): ?>

    /**
     * Introduce them to the guide and provide instructions
     */
    guiders.createGuider({
        buttons: [
            {name: "<?php echo $this->__("Let's Get Started!") ?>", onclick: guiders.next},
            {name: "<?php echo $this->__('No Thanks') ?>", onclick: guiders.hideAll}
        ],
        buttonCustomHTML: dontShowButtonHtml,
        description: "<?php echo $this->__(
            'This module allows you to set up an email to be sent after a specified number of days of an order reaching a specified status, prompting your customers to provide a review of the product(s) they purchased.' .
            "%sLet's get you set up!%sReady to Go?%s",
            '<br /><br />',
            '<br /><br /><div style=\"text-align:right; font-weight:bold;\">',
            '</div>'
        ) ?>",
        id: "start",
        next: "bronto_reviews-enable",
        overlay: true, closeOnEscape: true,
        title: "Bronto Extension - <?php echo $this->__('Review Requests Module') ?>",
        width: 600
    });

    /**
     * Enable the Module
     */
    guiders.createGuider({
        attachTo: '#bronto_reviews_settings_enabled',
        buttons: [
            {name: "<?php echo $this->__('Back') ?>"},
            {name: "<?php echo $this->__('Next') ?>", onclick: function() {
                if (jQuery('#bronto_reviews_settings_enabled').val() == '1') {
                    guiders.next();
                } else {
                    alert("<?php echo $this->__("Don't forget to enable the module.") ?>");
                }
            }},
            {name: "<?php echo $this->__('Close') ?>"}
        ],
        shouldSkip: function() {
            return <?php echo ($this->isDefaultScope()) ? 'false' : 'true'; ?>
        },
        autoFocus: true,
        highlight: '#bronto_reviews_settings_enabled',
        description: "<?php echo $this->__("Let's enable the module and expose some more options.  Just set `Enable Module` to Yes.") ?>",
        id: "bronto_reviews-enable",
        next: "bronto_reviews-order_status",
        position: 11,
        overlay: true, closeOnEscape: true,
        title: "<?php echo $this->__('Enable the Module') ?>",
        width: 200
    });

    /**
     * Save Configuration
     */
    guiders.createGuider({
        attachTo: 'button.save',
        buttons: [
            {name: "<?php echo $this->__('Back') ?>"},
            {name: "<?php echo $this->__('Save Config') ?>", onclick: function() {
                configForm.submit()
            }},
            {name: "<?php echo $this->__('Next') ?>"},
            {name: "<?php echo $this->__('Close') ?>"}
        ],
        shouldSkip: function() {
            return <?php echo ($this->isDefaultScope()) ? 'false' : 'true'; ?>
        },
        autoFocus: true,
        highlight: 'button.save',
        overlay: true, closeOnEscape: true,
        description: "<?php echo $this->__('Now that the initial settings have been configured, you should save them.  Click `Save Config` now.') ?>",
        id: "bronto_reviews-save_config_first",
        next: "bronto_reviews-order_status",
        position: 5,
        title: "<?php echo $this->__('Save Config') ?>"
    });

    /**
     * Explain the Order Status option
     */
    guiders.createGuider({
        attachTo: '#bronto_reviews_settings_status',
        buttons: [
            {name: "<?php echo $this->__('Back') ?>"},
            {name: "<?php echo $this->__('Next') ?>"},
            {name: "<?php echo $this->__('Close') ?>"}
        ],
        autoFocus: true,
        highlight: '#bronto_reviews_settings_status',
        description: "<?php echo $this->__("This setting allows you to specify the order status at which to trigger the delivery.  When an order reaches this status the system will send a delivery schedule request to Bronto to schedule an email to be sent after a specified number of days.") ?>",
        id: "bronto_reviews-order_status",
        next: "bronto_reviews-cancel_status",
        position: 11,
        overlay: true, closeOnEscape: true,
        title: "<?php echo $this->__('Order Status') ?>",
        width: 200
    });

    /**
     * Explain the Cancel Status Option
     */
    guiders.createGuider({
        attachTo: '#bronto_reviews_settings_cancel_status',
        buttons: [
            {name: "<?php echo $this->__('Back') ?>"},
            {name: "<?php echo $this->__('Next') ?>"},
            {name: "<?php echo $this->__('Close') ?>"}
        ],
        autoFocus: true,
        highlight: "#bronto_reviews_settings_cancel_status",
        description: "<?php echo $this->__('This setting allows you to specify the order status(s) which should cancel the scheduled delivery.  You will need to select a status that can be reached after a delivery has been placed, such as if your Order Status is set to `Complete`, your Cancel Delivery Status should be `Closed` as once an order is complete it can only be removed by refunding the order.') ?>",
        id: "bronto_reviews-cancel_status",
        next: "bronto_reviews-period",
        position: 10,
        overlay: true, closeOnEscape: true,
        title: "<?php echo $this->__('Cancel Order Status') ?>",
        width: 200
    });

    /**
     * Explain the Send Period Setting
     */
    guiders.createGuider({
        attachTo: '#bronto_reviews_settings_period',
        buttons: [
            {name: "<?php echo $this->__('Back') ?>"},
            {name: "<?php echo $this->__('Next') ?>"},
            {name: "<?php echo $this->__('Close') ?>"}
        ],
        autoFocus: true,
        highlight: "#bronto_reviews_settings_period",
        description: "<?php echo $this->__('The Send Period is the number of days to wait before sending the Review Request email.') ?>",
        id: "bronto_reviews-period",
        next: "bronto_reviews-message",
        position: 9,
        overlay: true, closeOnEscape: true,
        title: "<?php echo $this->__('Send Period') ?>",
        width: 200
    });

    /**
     * Explain the Review Request Message
     */
    guiders.createGuider({
        attachTo: '#bronto_reviews_settings_message',
        buttons: [
            {name: "<?php echo $this->__('Back') ?>"},
            {name: "<?php echo $this->__('Next') ?>"},
            {name: "<?php echo $this->__('Close') ?>"}
        ],
        autoFocus: true,
        highlight: "#bronto_reviews_settings_message",
        description: "<?php echo $this->__('Select the Bronto Message you want to use to send the Review Request email.') ?>",
        id: "bronto_reviews-message",
        next: "bronto_reviews-url_suffix",
        position: 9,
        overlay: true, closeOnEscape: true,
        title: "<?php echo $this->__('Review Request Message') ?>",
        width: 200
    });

    /**
     * Explain the Product Url Suffix
     */
    guiders.createGuider({
        attachTo: '#bronto_reviews_settings_url_suffix',
        buttons: [
            {name: "<?php echo $this->__('Back') ?>"},
            {name: "<?php echo $this->__('Next') ?>"},
            {name: "<?php echo $this->__('Close') ?>"}
        ],
        autoFocus: true,
        highlight: "#bronto_reviews_settings_url_suffix",
        description: "<?php echo $this->__('The Product URL Suffix allows you to append strings to the end of the product url.  This is useful if you want to add a hyperlink reference to a specific portion of the product page.') ?>",
        id: "bronto_reviews-url_suffix",
        next: "bronto_reviews-sender_email",
        position: 9,
        overlay: true, closeOnEscape: true,
        title: "<?php echo $this->__('Product URL Suffix') ?>",
        width: 200
    });

    /**
     * Explain the Sender Details
     */
    guiders.createGuider({
        attachTo: '#bronto_reviews_settings_sender_email',
        buttons: [
            {name: "<?php echo $this->__('Back') ?>"},
            {name: "<?php echo $this->__('Next') ?>"},
            {name: "<?php echo $this->__('Close') ?>"}
        ],
        autoFocus: true,
        closeOnEscape: true,
        description: "<?php echo $this->__('The Sender Email, Sender Name, and Reply To settings are what will be used for sending the Review Request emails.') ?>",
        id: "bronto_reviews-sender_email",
        next: "scope",
        position: 10,
        title: "<?php echo $this->__('Sender Details') ?>",
        width: 200
    });

    <?php if ($this->canShowGuide()): ?>
        guiders.show('start');
    <?php endif; ?>

<?php endif; ?>
