<?php
/**
* @author Amasty Team
* @copyright Copyright (c) 2012 Amasty (http://www.amasty.com)
* @package Amasty_Xnotif
*/   
?>
<?php $_productId = Mage::registry('product')->getId()?>
<div class="amxnotif-block">
	<label><?php echo $this->__('Subscribe to back in stock notification'); ?> </label><br/>
	<input type="text" name="guest_email" id="amxnotif_guest_email-<?php echo $_productId;?>" onKeyPress="return checkIt(event, '<?php echo $this->escapeHtml(Mage::helper('amxnotif')->getEmailUrl('stock'));?>', $('button-email-send-<?php echo $_productId;?>'))" class="input-text" size="30" placeholder="Your e-mail" />
	<input type="hidden" name="product_id" value="<?php echo $_productId;?>" />
	<input type="hidden" name="type" value="email" />
	<input type="hidden" name="parent_id" value="<?php echo Mage::registry('par_product_id')?>" />
	<input type="hidden" name="<?php echo Mage_Core_Controller_Front_Action::PARAM_NAME_URL_ENCODED ?>" value="<?php echo Mage::helper('amxnotif')->getEncodedUrl()?>" />
	<button type="button" id="button-email-send-<?php echo $_productId;?>" class="button btn-cart amcart-ignore" onclick="send_alert_email('<?php echo $this->escapeHtml(Mage::helper('amxnotif')->getEmailUrl('stock'));?>', this)" title="<?php echo $this->__('Subscribe'); ?>"><span><span><?php echo $this->__('Dazzle Me'); ?></span> <i class="icon-mail"></i></span> </button>
	<div class="amxnotif-privacy"><a href="http://www.blingjewelry.com/privacy-policy-i-3.html" target="_blank">Privacy policy</a></div>
</div>  

 
